[project]
name = "financial-analysis"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dlt[postgres]>=1.29.1",
    "google-genai>=2.17.0",
    "jupyter>=1.1.1",
    "openpyxl>=3.1.5",
    "pgvector>=0.5.0",
    "playwright>=1.62.0",
    "psycopg>=3.3.4",
    "psycopg2-binary>=2.9.12",
    "pymupdf>=1.28.0",
    "python-dotenv>=1.2.2",
    "python-pptx>=1.0.2",
    "requests>=2.34.2",
    "sentence-transformers>=5.7.0",
    "tabulate>=0.10.0",
]
