[project]
name = "financial-analysis"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dlt[postgres]>=1.29.1",
    "playwright>=1.62.0",
    "psycopg>=3.3.4",
    "psycopg2-binary>=2.9.12",
    "pymupdf>=1.28.0",
    "python-dotenv>=1.2.2",
    "requests>=2.34.2",
    "tabulate>=0.10.0",
]
