from __future__ import annotations

import argparse
import json
from typing import Any

from agent.gemini import GeminiFinancialAgent
from agent.pipeline import run_agent
from ingestion.processing.database import load_environment


def print_value(
    value: Any,
    *,
    indent: int = 2,
) -> None:
    """
    Pretty-print arbitrary Python values.
    """

    prefix = " " * indent

    if isinstance(
        value,
        (
            dict,
            list,
        ),
    ):
        formatted = json.dumps(
            value,
            indent=2,
            ensure_ascii=False,
            default=str,
        )

        for line in formatted.splitlines():
            print(f"{prefix}{line}")

        return

    print(f"{prefix}{value}")


def print_arguments(
    arguments: dict[str, Any],
) -> None:
    """
    Pretty-print arguments generated by Gemini for a tool call.
    """

    if not arguments:
        print("  None")
        return

    for key, value in arguments.items():
        if isinstance(
            value,
            (
                dict,
                list,
            ),
        ):
            print(f"  {key}:")

            print_value(
                value,
                indent=4,
            )

        else:
            print(f"  {key}: {value}")


def unwrap_tool_response(
    response: Any,
) -> Any:
    """
    Unwrap Gemini's automatic function response.

    Gemini may wrap a Python tool's return value like:

        {
            "result": {
                ...
            }
        }

    This function returns the underlying tool result when that
    wrapper is present.
    """

    if not isinstance(
        response,
        dict,
    ):
        return response

    if "result" in response and isinstance(
        response["result"],
        dict,
    ):
        return response["result"]

    return response


def print_tool_response(
    response: Any,
) -> None:
    """
    Print a concise interpretation of a tool response.
    """

    if response is None:
        print("  No tool response captured.")
        return

    response = unwrap_tool_response(response)

    if not isinstance(
        response,
        dict,
    ):
        print_value(
            response,
            indent=2,
        )
        return

    # =========================================================
    # SDK-level error
    # =========================================================

    if "error" in response and "success" not in response:
        print("  Status: FAILED")

        print("  Error: " f"{response['error']}")

        return

    # =========================================================
    # Application-level result
    # =========================================================

    success = response.get("success")

    if success is False:
        print("  Status: FAILED")

        error_type = response.get("error_type")

        if error_type:
            print("  Error type: " f"{error_type}")

        error = response.get("error")

        if error:
            print("  Error: " f"{error}")

        return

    print("  Status: SUCCESS")

    # =========================================================
    # Retrieval result
    # =========================================================

    count = response.get("count")

    if count is not None:
        print("  Results returned: " f"{count}")

    # =========================================================
    # Calculator result
    # =========================================================

    if "result" in response and not isinstance(
        response["result"],
        dict,
    ):
        print("  Result: " f"{response['result']}")

    # =========================================================
    # Table result
    # =========================================================

    if response.get("found") is True:
        table_id = response.get("table_id")

        if table_id:
            print("  Table ID: " f"{table_id}")

        page_number = response.get("pdf_page_number")

        if page_number is not None:
            print("  PDF page: " f"{page_number}")

    # =========================================================
    # Web search result
    # =========================================================

    if response.get("answer"):
        answer = str(response["answer"])

        preview_length = 500

        if len(answer) > preview_length:
            answer = answer[:preview_length] + "..."

        print("  Web response preview:")

        print(f"    {answer}")

        sources = response.get(
            "sources",
            [],
        )

        if sources:
            print("  Web sources:")

            for source in sources:
                title = source.get(
                    "title",
                    "Web source",
                )

                url = source.get(
                    "url",
                    "",
                )

                print(f"    - {title}: {url}")


def main() -> None:
    parser = argparse.ArgumentParser(
        description=("Test the two-stage " "financial-analysis agent.")
    )

    parser.add_argument(
        "question",
        help=("Financial-analysis question " "to ask."),
    )

    parser.add_argument(
        "--ticker",
        default=None,
        help=("Optional ticker filter for " "initial annual-report retrieval."),
    )

    parser.add_argument(
        "--year",
        type=int,
        default=None,
        help=("Optional report-year filter " "for initial retrieval."),
    )

    parser.add_argument(
        "--top-k",
        type=int,
        default=8,
        help=("Number of documents returned " "by initial hybrid retrieval."),
    )

    parser.add_argument(
        "--model",
        default="gemini-2.5-flash",
        help="Gemini model.",
    )

    parser.add_argument(
        "--max-tool-calls",
        type=int,
        default=8,
        help=("Maximum number of additional " "automatic tool calls."),
    )

    parser.add_argument(
        "--show-context",
        action="store_true",
        help=("Print the initial retrieved " "annual-report context."),
    )

    parser.add_argument(
        "--show-raw-tools",
        action="store_true",
        help=("Print raw Gemini tool responses " "for debugging."),
    )

    args = parser.parse_args()

    # =========================================================
    # Environment
    # =========================================================

    load_environment()

    # =========================================================
    # Agent
    # =========================================================

    agent = GeminiFinancialAgent(
        model=args.model,
        max_tool_calls=(args.max_tool_calls),
    )

    # =========================================================
    # Run agent
    # =========================================================

    result = run_agent(
        args.question,
        agent=agent,
        ticker=args.ticker,
        report_year=args.year,
        top_k=args.top_k,
    )

    # =========================================================
    # Query information
    # =========================================================

    print()
    print("=" * 80)
    print("QUERY")
    print("=" * 80)

    print("Original user query:")

    print(result["question"])

    print()

    print("Initial retrieval query:")

    print(result["initial_retrieval_query"])

    print()

    rewritten = result["question"] != result["initial_retrieval_query"]

    print("Initial query rewritten:")

    print("Yes" if rewritten else "No")

    # =========================================================
    # Initial context
    # =========================================================

    if args.show_context:
        print()
        print("=" * 80)
        print("INITIAL ANNUAL-REPORT CONTEXT")
        print("=" * 80)

        print(result["initial_context"])

    # =========================================================
    # Tools
    # =========================================================

    print()
    print("=" * 80)
    print("TOOLS USED")
    print("=" * 80)

    # ---------------------------------------------------------
    # Pipeline-controlled initial retrieval
    # ---------------------------------------------------------

    print("Initial pipeline tool:")

    print("  Tool: search_hybrid")

    print("  Query: " f"{result['initial_retrieval_query']}")

    if result.get("ticker") is not None:
        print("  Ticker: " f"{result['ticker']}")

    if result.get("report_year") is not None:
        print("  Report year: " f"{result['report_year']}")

    initial_retrieval = result.get(
        "initial_retrieval",
        {},
    )

    if initial_retrieval.get("success") is False:
        print("  Status: FAILED")

        error_type = initial_retrieval.get("error_type")

        if error_type:
            print("  Error type: " f"{error_type}")

        print("  Error: " f"{initial_retrieval.get('error')}")

    else:
        print("  Status: SUCCESS")

        count = initial_retrieval.get("count")

        if count is not None:
            print("  Results returned: " f"{count}")

    # ---------------------------------------------------------
    # Gemini-selected tools
    # ---------------------------------------------------------

    tool_calls = result.get(
        "tool_calls",
        [],
    )

    print()

    print("Additional tools selected by Gemini:")

    if not tool_calls:
        print("  None")

    else:
        for call in tool_calls:
            print()
            print("-" * 80)

            print("Tool call " f"{call['call_number']}")

            print("Tool: " f"{call['tool']}")

            print("Arguments:")

            print_arguments(
                call.get(
                    "arguments",
                    {},
                )
            )

            if args.show_raw_tools:
                print("Raw tool response:")

                print_value(
                    call.get("response"),
                    indent=2,
                )

            print("Tool response:")

            print_tool_response(call.get("response"))

    # =========================================================
    # Answer
    # =========================================================

    print()
    print("=" * 80)
    print("ANSWER")
    print("=" * 80)

    print(result["answer"])

    # =========================================================
    # Timing
    # =========================================================

    timing = result["timing"]

    print()
    print("=" * 80)
    print("TIMING")
    print("=" * 80)

    print("Initial retrieval: " f"{timing['initial_retrieval_seconds']:.4f} s")

    print("Agent stage:       " f"{timing['agent_seconds']:.4f} s")

    print("Total:             " f"{timing['total_seconds']:.4f} s")


if __name__ == "__main__":
    main()
